services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: celery -A worker.tasks worker -Q default -l INFO
    env_file: .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - api
      - db
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: toolkit
      POSTGRES_PASSWORD: toolkit
      POSTGRES_DB: toolkit
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
