services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: ./.env
    environment:
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MODEL: ${LLM_MODEL:-gpt-4.1-mini}
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: celery -A worker.tasks worker -Q default -l INFO
    env_file: ./.env
    environment:
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MODEL: ${LLM_MODEL:-gpt-4.1-mini}
    volumes:
      - ./:/usr/src/app
    depends_on:
      api:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: toolkit
      POSTGRES_PASSWORD: toolkit
      POSTGRES_DB: toolkit
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toolkit -d toolkit || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 20
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
